library(downloader)
library(dplyr)

url <- "https://raw.githubusercontent.com/genomicsclass/dagdata/master/inst/extdata/babies.txt"
filename <- basename(url)
download(url, destfile=filename)
babies <- read.table("babies.txt", header=TRUE)

bwt.nonsmoke <- filter(babies, smoke==0) %>% select(bwt) %>% unlist 
bwt.smoke <- filter(babies, smoke==1) %>% select(bwt) %>% unlist

library(rafalib)
mean(bwt.nonsmoke)-mean(bwt.smoke)
popsd(bwt.nonsmoke)
popsd(bwt.smoke)

# Exercise 1: t-distribution approximation
set.seed(1)
N <- 25
sample_nonsmoke <- sample(bwt.nonsmoke, N)
sample_smoke <- sample(bwt.smoke, N)

qt(.995, df=48) * sqrt(sd(sample_nonsmoke)^2/N + sd(sample_smoke)^2/N )

# Exercise 2: Which of the following sentences about a Type I error is not true?
# O - The following is another way to describe the Type I error: you decided to
#     reject the null hypothesis on the basis of data that was actually generated
#     by the null hypothesis
# 
# O - The following is the another way to describe a Type I error: due to random 
#     fluctuations, even though the data you observed were actually generated by
#     the null hypothesis, the p-value calculated from the observed data was 
#     small, so you rejected it.
#
# X - From the original data alone, you can tell whether you have made a Type I error
# 
# O - In scientific practice, a Type I error constitutes reporting a 
#     "significant" result when there is actually no result

# Exercise 3: t-test
set.seed(1)
N <- 5
sample_nonsmoke <- sample(bwt.nonsmoke, N)
sample_smoke <- sample(bwt.smoke, N)

t.test(sample_nonsmoke, sample_smoke)$p.value # p-value: 0.1843
